# Update and install Apache on Ubuntu
sudo yum update -y
sudo yum install -y httpd.x86_64

# Start and enable Apache service
sudo systemctl start httpd.service
sudo systemctl enable httpd.service

# Fetch EC2 instance metadata using IMDSv2
TOKEN=$(curl --request PUT "http://169.254.169.254/latest/api/token" --header "X-aws-ec2-metadata-token-ttl-seconds: 3600")

instanceId=$(curl -s http://169.254.169.254/latest/meta-data/instance-id --header "X-aws-ec2-metadata-token: $TOKEN")
instanceAZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone --header "X-aws-ec2-metadata-token: $TOKEN")
privHostName=$(curl -s http://169.254.169.254/latest/meta-data/local-hostname --header "X-aws-ec2-metadata-token: $TOKEN")
privIPv4=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4 --header "X-aws-ec2-metadata-token: $TOKEN")
AMI_ID=$(curl -s http://169.254.169.254/latest/meta-data/ami-id \  --header "X-aws-ec2-metadata-token: $TOKEN")
              
# Write HTML output to Apache's web root
cat <<EOF | sudo tee /var/www/html/index.html > /dev/null
<font face="Verdana" size="5">
  <center><h1>AWS Linux VM from AMI generated by PACKER </h1></center>
  <center><b>EC2 Instance Metadata</b></center>
  <center><b>AMI ID:</b> $AMI_ID</center>
  <center><b>Instance ID:</b> $instanceId</center>
  <center><b>AWS Availability Zone:</b> $instanceAZ</center>
  <center><b>Private Hostname:</b> $privHostName</center>
  <center><b>Private IPv4:</b> $privIPv4</center>
</font>
EOF